import Image from 'next/image'
import Search from '@/components/shared/Search'
import Card from '@/components/shared/Card'
import { getAllImages } from "@/lib/actions/image.actions"

type imageProps = {
  title: string;
  prompt: string;
  imageUrl: string;
};

const CommunityPage = async() => {
  const images = await getAllImages()

  return (
    <main className='w-full h-full flex flex-col items-center'>
      <div className='w-full flex flex-col items-center mt-28'>
        <h1 className='text-3xl font-extrabold mb-2 text-gray-700'>Community Showcase</h1>
        <h4 className='mb-6 text-gray-500 max-w-[500px] text-center'>Browse through a collection of imaginative and visually stunning images generated by artifex</h4>
        <Search/>
      </div>
      <div className='w-11/12 flex flex-col lg:flex-row items-center gap-8'>
        {
            images && images.map((image: imageProps) => (
                <Card image={image}/>
            ))
        }
      </div>
    </main>
  )
}

export default CommunityPage